# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
podfile: Example/Podfile
osx_image: xcode13.1

before_install:
#  - gem install xcpretty cocoapods --pre # Since Travis is not always on latest version
   - pod repo update
   - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -workspace Example/StravaSwift.xcworkspace -scheme StravaSwift-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' | xcpretty
  - pod lib lint --allow-warnings
